In [1]:
import pandas as pd

convert to parquet whatever that is!

Data from this link https://www2.census.gov/programs-surveys/popest/datasets/2000-2010/intercensal/county/   
previously called co-est00int-tot.csv

In [2]:
popdata = pd.read_csv("popestimate_2000_2010.csv", encoding="ISO-8859-1")
popdata.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,ESTIMATESBASE2000,POPESTIMATE2000,POPESTIMATE2001,POPESTIMATE2002,POPESTIMATE2003,POPESTIMATE2004,POPESTIMATE2005,POPESTIMATE2006,POPESTIMATE2007,POPESTIMATE2008,POPESTIMATE2009,CENSUS2010POP,POPESTIMATE2010
0,40,3,6,1,0,Alabama,Alabama,4447207,4452173,4467634,4480089,4503491,4530729,4569805,4628981,4672840,4718206,4757938,4779736,4785298
1,50,3,6,1,1,Alabama,Autauga County,43751,44021,44889,45909,46800,48366,49676,51328,52405,53277,54135,54571,54632
2,50,3,6,1,3,Alabama,Baldwin County,140416,141342,144875,147957,151509,156266,162183,168121,172404,175827,179406,182265,183195
3,50,3,6,1,5,Alabama,Barbour County,29042,29015,28863,28653,28594,28287,28027,27861,27757,27808,27657,27457,27411
4,50,3,6,1,7,Alabama,Bibb County,19856,19913,21028,21199,21399,21721,22042,22099,22438,22705,22941,22915,22867

In [20]:
popdata.columns

Index(['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME',
       'ESTIMATESBASE2000', 'POPESTIMATE2000', 'POPESTIMATE2001',
       'POPESTIMATE2002', 'POPESTIMATE2003', 'POPESTIMATE2004',
       'POPESTIMATE2005', 'POPESTIMATE2006', 'POPESTIMATE2007',
       'POPESTIMATE2008', 'POPESTIMATE2009', 'CENSUS2010POP',
       'POPESTIMATE2010'],
      dtype='object')

In [3]:
popdata_after2010 = pd.read_csv("popestimate_2010_2019.csv", encoding="ISO-8859-1")
popdata_after2010.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2019,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016,RNETMIG2017,RNETMIG2018,RNETMIG2019
0,40,3,6,1,0,Alabama,Alabama,4779736,4780125,4785437,...,1.917501,0.578434,1.186314,1.522549,0.563489,0.626357,0.745172,1.090366,1.773786,2.483744
1,50,3,6,1,1,Alabama,Autauga County,54571,54597,54773,...,4.847310,6.018182,-6.226119,-3.902226,1.970443,-1.712875,4.777171,0.849656,0.540916,4.560062
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183112,...,24.017829,16.641870,17.488579,22.751474,20.184334,17.725964,21.279291,22.398256,24.727215,24.380567
3,50,3,6,1,5,Alabama,Barbour County,27457,27455,27327,...,-5.690302,0.292676,-6.897817,-8.132185,-5.140431,-15.724575,-18.238016,-24.998528,-8.754922,-5.165664
4,50,3,6,1,7,Alabama,Bibb County,22915,22915,22870,...,1.385134,-4.998356,-3.787545,-5.797999,1.331144,1.329817,-0.708717,-3.234669,-6.857092,1.831952

In [17]:
popdata_after2010.columns

Index(['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME',
       'CENSUS2010POP', 'ESTIMATESBASE2010', 'POPESTIMATE2010',
       ...
       'RDOMESTICMIG2019', 'RNETMIG2011', 'RNETMIG2012', 'RNETMIG2013',
       'RNETMIG2014', 'RNETMIG2015', 'RNETMIG2016', 'RNETMIG2017',
       'RNETMIG2018', 'RNETMIG2019'],
      dtype='object', length=164)

In [22]:
popdata_after2010 = popdata_after2010[
    [
        "SUMLEV",
        "REGION",
        "DIVISION",
        "STATE",
        "COUNTY",
        "STNAME",
        "CTYNAME",
        "CENSUS2010POP",
        "ESTIMATESBASE2010",
        "POPESTIMATE2010",
        "POPESTIMATE2011",
        "POPESTIMATE2012",
        "POPESTIMATE2013",
        "POPESTIMATE2014",
        "POPESTIMATE2015",
        "POPESTIMATE2016",
        "POPESTIMATE2017",
        "POPESTIMATE2018",
    ]
]

popdata_after2010.columns

Index(['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME',
       'CENSUS2010POP', 'ESTIMATESBASE2010', 'POPESTIMATE2010',
       'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013',
       'POPESTIMATE2014', 'POPESTIMATE2015', 'POPESTIMATE2016',
       'POPESTIMATE2017', 'POPESTIMATE2018'],
      dtype='object')

In [25]:
new_dataset = pd.merge(popdata, popdata_after2010, on=["STATE", "COUNTY"])
new_dataset.head()

,SUMLEV_x,REGION_x,DIVISION_x,STATE,COUNTY,STNAME_x,CTYNAME_x,ESTIMATESBASE2000,POPESTIMATE2000,POPESTIMATE2001,...,ESTIMATESBASE2010,POPESTIMATE2010_y,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018
0,40,3,6,1,0,Alabama,Alabama,4447207,4452173,4467634,...,4780125,4785437,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681
1,50,3,6,1,1,Alabama,Autauga County,43751,44021,44889,...,54597,54773,55227,54954,54727,54893,54864,55243,55390,55533
2,50,3,6,1,3,Alabama,Baldwin County,140416,141342,144875,...,182265,183112,186558,190145,194885,199183,202939,207601,212521,217855
3,50,3,6,1,5,Alabama,Barbour County,29042,29015,28863,...,27455,27327,27341,27169,26937,26755,26283,25806,25157,24872
4,50,3,6,1,7,Alabama,Bibb County,19856,19913,21028,...,22915,22870,22745,22667,22521,22553,22566,22586,22550,22367

In [4]:
popdata["REGION"].value_counts()

REGION
3    1440
2    1067
4     461
1     226
Name: count, dtype: int64

In [5]:
popdata_edit = popdata.copy()
popdata_edit = popdata_edit.drop(columns=["SUMLEV", "REGION", "DIVISION"])
popdata_edit.head()

,STATE,COUNTY,STNAME,CTYNAME,ESTIMATESBASE2000,POPESTIMATE2000,POPESTIMATE2001,POPESTIMATE2002,POPESTIMATE2003,POPESTIMATE2004,POPESTIMATE2005,POPESTIMATE2006,POPESTIMATE2007,POPESTIMATE2008,POPESTIMATE2009,CENSUS2010POP,POPESTIMATE2010
0,1,0,Alabama,Alabama,4447207,4452173,4467634,4480089,4503491,4530729,4569805,4628981,4672840,4718206,4757938,4779736,4785298
1,1,1,Alabama,Autauga County,43751,44021,44889,45909,46800,48366,49676,51328,52405,53277,54135,54571,54632
2,1,3,Alabama,Baldwin County,140416,141342,144875,147957,151509,156266,162183,168121,172404,175827,179406,182265,183195
3,1,5,Alabama,Barbour County,29042,29015,28863,28653,28594,28287,28027,27861,27757,27808,27657,27457,27411
4,1,7,Alabama,Bibb County,19856,19913,21028,21199,21399,21721,22042,22099,22438,22705,22941,22915,22867

In [6]:
# there are rows where state and county name are the same. I am assuming this is the population of the whole state. going to save that to another data set lol
statepop_data = popdata_edit[popdata_edit["STNAME"] == popdata_edit["CTYNAME"]]
len(statepop_data)

# also going to drop the state data from the county dataset
county_popdata = popdata_edit[popdata_edit["STNAME"] != popdata_edit["CTYNAME"]]
county_popdata.head()

,STATE,COUNTY,STNAME,CTYNAME,ESTIMATESBASE2000,POPESTIMATE2000,POPESTIMATE2001,POPESTIMATE2002,POPESTIMATE2003,POPESTIMATE2004,POPESTIMATE2005,POPESTIMATE2006,POPESTIMATE2007,POPESTIMATE2008,POPESTIMATE2009,CENSUS2010POP,POPESTIMATE2010
1,1,1,Alabama,Autauga County,43751,44021,44889,45909,46800,48366,49676,51328,52405,53277,54135,54571,54632
2,1,3,Alabama,Baldwin County,140416,141342,144875,147957,151509,156266,162183,168121,172404,175827,179406,182265,183195
3,1,5,Alabama,Barbour County,29042,29015,28863,28653,28594,28287,28027,27861,27757,27808,27657,27457,27411
4,1,7,Alabama,Bibb County,19856,19913,21028,21199,21399,21721,22042,22099,22438,22705,22941,22915,22867
5,1,9,Alabama,Blount County,50982,51107,51845,52551,53457,54124,54624,55485,56240,57055,57341,57322,57338

Okay so now we have population estimates for every county (and state!) from 2000 to 2010
But! we need 2010-2018/2019

also need FIPS codes

### FIP Codes

looks like each state has its own FIPS code data set. thats slightly annoying

Lets just try Alabama and see how it goes

In [7]:
# Alabama
alabama_fips = pd.read_csv(
    "https://www2.census.gov/geo/docs/reference/codes2020/cou/st01_al_cou2020.txt",
    delimiter="|",
)
alabama_fips

   STATE  STATEFP  COUNTYFP  COUNTYNS         COUNTYNAME CLASSFP FUNCSTAT
0     AL        1         1    161526     Autauga County      H1        A
1     AL        1         3    161527     Baldwin County      H1        A
2     AL        1         5    161528     Barbour County      H1        A
3     AL        1         7    161529        Bibb County      H1        A
4     AL        1         9    161530      Blount County      H1        A
..   ...      ...       ...       ...                ...     ...      ...
62    AL        1       125    161588  Tuscaloosa County      H1        A
63    AL        1       127    161589      Walker County      H1        A
64    AL        1       129    161590  Washington County      H1        A
65    AL        1       131    161591      Wilcox County      H1        A
66    AL        1       133    161592     Winston County      H1        A

[67 rows x 7 columns]

In [8]:
alabama_fips["STATEFP"] = alabama_fips["STATEFP"].astype(str)
alabama_fips["COUNTYFP"] = alabama_fips["COUNTYFP"].astype(str)

In [9]:
alabama_fips["FIPS_code"] = alabama_fips["STATEFP"] + alabama_fips["COUNTYFP"]
alabama_fips.head(10)

  STATE STATEFP COUNTYFP  COUNTYNS       COUNTYNAME CLASSFP FUNCSTAT FIPS_code
0    AL       1        1    161526   Autauga County      H1        A        11
1    AL       1        3    161527   Baldwin County      H1        A        13
2    AL       1        5    161528   Barbour County      H1        A        15
3    AL       1        7    161529      Bibb County      H1        A        17
4    AL       1        9    161530    Blount County      H1        A        19
5    AL       1       11    161531   Bullock County      H1        A       111
6    AL       1       13    161532    Butler County      H1        A       113
7    AL       1       15    161533   Calhoun County      H1        A       115
8    AL       1       17    161534  Chambers County      H1        A       117
9    AL       1       19    161535  Cherokee County      H1        A       119

### Actually!
I found a data set that has all the states and their county FIPS code, so im gonna use that  
https://transition.fcc.gov/oet/info/maps/census/fips/fips.txt  
I just googled county FIPS codes and this popped up
### so like never mind to all the stuff between here and the FIPS code earlier

In [10]:
state_county_FIPS = pd.read_fwf(
    "state_county_FIPS.txt", header=None, names=["county_level_FIPS", "place"]
)
state_county_FIPS.head()

                county_level_FIPS  place
0      county-level_FIPS    place    NaN
1  ------------    --------------    NaN
2            01000        Alabama    NaN
3     01001        Autauga County    NaN
4     01003        Baldwin County    NaN

having a lot of difficulty reading this in...  
im gonna put it into google sheets to fix it and then save it as a csv :)))

### nevermind...  
I found the codes in a decent format on wikipedia, but assumed Nick would really not like us using Wikipedia, so I am going to just use the census website like i was at the start  

### wait
there is a data set that has all US states.
resisting the urge to use inappropriate language here.  
anyway continuing on then now using that..

In [11]:
state_county_FIPS = pd.read_csv(
    "https://www2.census.gov/geo/docs/reference/codes2020/national_county2020.txt",
    delimiter="|",
)
state_county_FIPS.head()

  STATE  STATEFP  COUNTYFP  COUNTYNS      COUNTYNAME CLASSFP FUNCSTAT
0    AL        1         1    161526  Autauga County      H1        A
1    AL        1         3    161527  Baldwin County      H1        A
2    AL        1         5    161528  Barbour County      H1        A
3    AL        1         7    161529     Bibb County      H1        A
4    AL        1         9    161530   Blount County      H1        A

but this is actually the same issue as earlier where alabama is 1 instead of "01", and Autauga county is 1 instead of "001"

In [12]:
# making it a string so they are easier to concatenate
state_county_FIPS["STATEFP"] = state_county_FIPS["STATEFP"].astype(str)
state_county_FIPS["COUNTYFP"] = state_county_FIPS["COUNTYFP"].astype(str)

# adding a 0 onto the front of those that are only one digit
state_county_FIPS["STATEFP"] = state_county_FIPS["STATEFP"].astype(str).str.zfill(2)
state_county_FIPS.head()

# adding 0s as needed to make it 3 digits
state_county_FIPS["COUNTYFP"] = state_county_FIPS["COUNTYFP"].astype(str).str.zfill(3)
state_county_FIPS.sample(5)

# slayyyy

     STATE STATEFP COUNTYFP  COUNTYNS           COUNTYNAME CLASSFP FUNCSTAT
2346    SC      45      059   1248009       Laurens County      H1        A
627     IL      17      063    424233        Grundy County      H1        A
2953    VA      51      840   1789077      Winchester city      C7        F
2037    ND      38      093   1034224      Stutsman County      H1        A
2329    SC      45      025   1247989  Chesterfield County      H1        A

Okay now that I did that we need to actually concatenate to make the full FIPS code

In [13]:
state_county_FIPS["FIP_CODE"] = (
    state_county_FIPS["STATEFP"] + state_county_FIPS["COUNTYFP"]
)
state_county_FIPS.head()

  STATE STATEFP COUNTYFP  COUNTYNS      COUNTYNAME CLASSFP FUNCSTAT FIP_CODE
0    AL      01      001    161526  Autauga County      H1        A    01001
1    AL      01      003    161527  Baldwin County      H1        A    01003
2    AL      01      005    161528  Barbour County      H1        A    01005
3    AL      01      007    161529     Bibb County      H1        A    01007
4    AL      01      009    161530   Blount County      H1        A    01009

## merge pop data and FIPS  
now we can merge it with the population data from earlier

In [14]:
county_popdata.head()

# county_popdata has the states spelt, state_county_FIPS has the abbreviation

,STATE,COUNTY,STNAME,CTYNAME,ESTIMATESBASE2000,POPESTIMATE2000,POPESTIMATE2001,POPESTIMATE2002,POPESTIMATE2003,POPESTIMATE2004,POPESTIMATE2005,POPESTIMATE2006,POPESTIMATE2007,POPESTIMATE2008,POPESTIMATE2009,CENSUS2010POP,POPESTIMATE2010
1,1,1,Alabama,Autauga County,43751,44021,44889,45909,46800,48366,49676,51328,52405,53277,54135,54571,54632
2,1,3,Alabama,Baldwin County,140416,141342,144875,147957,151509,156266,162183,168121,172404,175827,179406,182265,183195
3,1,5,Alabama,Barbour County,29042,29015,28863,28653,28594,28287,28027,27861,27757,27808,27657,27457,27411
4,1,7,Alabama,Bibb County,19856,19913,21028,21199,21399,21721,22042,22099,22438,22705,22941,22915,22867
5,1,9,Alabama,Blount County,50982,51107,51845,52551,53457,54124,54624,55485,56240,57055,57341,57322,57338

In [15]:
# changing state_county_FIPS ['STATE'] to be the spelled out instead of abbreviation
# Create a dictionary to map state abbreviations to full names
state_abbreviation_to_full = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
}

# Map the abbreviations to full names
state_county_FIPS["STATE"] = state_county_FIPS["STATE"].map(state_abbreviation_to_full)

# Display the first few rows to verify the transformation
state_county_FIPS.head(10)

,STATE,STATEFP,COUNTYFP,COUNTYNS,COUNTYNAME,CLASSFP,FUNCSTAT,FIP_CODE
0,Alabama,01,001,161526,Autauga County,H1,A,01001
1,Alabama,01,003,161527,Baldwin County,H1,A,01003
2,Alabama,01,005,161528,Barbour County,H1,A,01005
3,Alabama,01,007,161529,Bibb County,H1,A,01007
4,Alabama,01,009,161530,Blount County,H1,A,01009
5,Alabama,01,011,161531,Bullock County,H1,A,01011
6,Alabama,01,013,161532,Butler County,H1,A,01013
7,Alabama,01,015,161533,Calhoun County,H1,A,01015
8,Alabama,01,017,161534,Chambers County,H1,A,01017
9,Alabama,01,019,161535,Cherokee County,H1,A,01019

okay now we can finally merge them lol

do a reshape